AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates a stackset containing the resources needed to get telemetry for AWS deployments in each region.

Resources:
  MarketplaceTelemetryResources:
    Type: AWS::CloudFormation::StackSet
    Properties:
      Capabilities: 
        - CAPABILITY_IAM
      StackSetName: 'TelemetryResources'
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - Regions:
            - af-south-1
            - eu-north-1
            - ap-south-1
            - eu-west-3
            - eu-west-2
            - eu-south-1
            - eu-west-1
            - ap-northeast-3
            - ap-northeast-2
            - me-south-1
            - ap-northeast-1
            - sa-east-1
            - ca-central-1
            - ap-east-1
            - ap-southeast-1
            - ap-southeast-2
            - eu-central-1
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
          DeploymentTargets:
            Accounts:
              - !Ref 'AWS::AccountId'
      TemplateBody: |
        Resources:
          EventBusRole:
            Type: 'AWS::IAM::Role'
            Properties:
              Description: IAM Role to be assumed by EventBus for pushing events
              AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Effect: Allow
                    Principal:
                      Service:
                        - events.amazonaws.com
                    Action:
                      - 'sts:AssumeRole'
              Path: /
              Policies:
                - PolicyName: root
                  PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'cloudwatch:*'
                          - 'logs:*'
                        Resource: '*'

          TelemetryEventBus:
            Type: AWS::Events::EventBus
            Properties:
                Name: "telemetry"

          TelemetryEventBusPolicy:
            Type: AWS::Events::EventBusPolicy
            Properties:
              EventBusName: !GetAtt TelemetryEventBus.Name
              StatementId: "AllowAll"
              Statement:
                Effect: "Allow"
                Principal: "*"
                Action: "events:PutEvents"
                Resource: !GetAtt TelemetryEventBus.Arn

          TelemetryLogGroup:
            Type: AWS::Logs::LogGroup
            Properties:
              LogGroupName: '/aws/events/uipath/telemetry'

          EventBusRule:
            Type: 'AWS::Events::Rule'
            Properties:
              Description: Push Event bus events
              EventBusName: !Ref TelemetryEventBus
              EventPattern:
                source:
                  - uipath-deployments
              State: ENABLED
              Targets:
                - Arn: !GetAtt TelemetryLogGroup.Arn
                  Id: uipath-deployments
