---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template used to deploy telemetry related services on target'
Parameters:
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: S3 bucket name hosting the Quickstart templates.
    Type: String
    Default: aws-quickstart
  QSS3BucketRegion:
    Default: us-east-1
    Description: >-
      The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted.
      When using your own bucket, you must specify this value.
    Type: String
    AllowedPattern: (us(-gov)?|ap|ca|cn|eu|sa)-(central|(north|south)?(east|west)?)-\d
    ConstraintDescription: Quick Start bucket region must be a valid AWS Region code.
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*/$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, and hyphens (-), and ending with a slash(/).
    Default: quickstart-uipath-orchestrator/
    Description: S3 key prefix under which Quick Start templates are hosted.
    Type: String

Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - aws-quickstart
Resources:
  EventBusRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: IAM Role to be assumed by EventBus for pushing events
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:*'
                  - 'logs:*'
                Resource: '*'

  TelemetryEventBus:
    Type: AWS::Events::EventBus
    Properties:
        Name: "telemetry"

  TelemetryEventBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !GetAtt TelemetryEventBus.Name
      StatementId: "AllowAll"
      Statement:
        Effect: "Allow"
        Principal: "*"
        Action: "events:PutEvents"
        Resource: !GetAtt TelemetryEventBus.Arn

  TelemetryLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/events/uipath/telemetry'

  EventBusRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: Push Event bus events
      EventBusName: !Ref TelemetryEventBus
      EventPattern:
        source:
          - uipath-deployments
      State: ENABLED
      Targets:
        - Arn: !GetAtt TelemetryLogGroup.Arn
          Id: uipath-deployments
