AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates a stackset containing S3 buckets in each region which will be used by the Orchestrator AWS marketplace deployment.
Parameters: 
  BucketBaseName:
    Description: The base name for the S3 Buckets
    Type: String
Resources:
  MarketplaceOrchestratorS3Bucket:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: 'S3AllRegionsBuckets'
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - Regions:
            - af-south-1
            - eu-north-1
            - ap-south-1
            - eu-west-3
            - eu-west-2
            - eu-south-1
            - eu-west-1
            - ap-northeast-3
            - ap-northeast-2
            - me-south-1
            - ap-northeast-1
            - sa-east-1
            - ca-central-1
            - ap-east-1
            - ap-southeast-1
            - ap-southeast-2
            - eu-central-1
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
          DeploymentTargets:
            Accounts:
              - !Ref 'AWS::AccountId'
      TemplateBody: !Sub
        - |
            Resources:
              s3Bucket:
                Type: AWS::S3::Bucket
                Properties:
                  BucketName: !Join
                    - ""
                    - - ${BucketBaseName}
                      - !Ref "AWS::Region"
        - { BucketBaseName: !Ref BucketBaseName }
                  